
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:8
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
        JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

server-defaults: &server-defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:8
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
        JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed
        DATABASE_URL: postgres://root:@localhost/ims
        DATABASE_NAME: ims
    - image: mdillon/postgis:10-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: ims
        POSTGRES_PASSWORD: ""

restore_cache: &restore_cache
  restore_cache:
    keys:
      - code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json"}}
      - code-master-{{ checksum ".nvmrc" }}-{{ checksum "package.json"}}

save_cache: &save_cache
  save_cache:
    key: code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json"}}
    paths:
      - node_modules

test-coverage: &test-coverage
  run: npx codecov && rm -rf codecov

version: 2
jobs:
  test:
    <<: *server-defaults
    steps:
      - checkout
      - *restore_cache
      - run: yarn
      - run: yarn run eslint
      - run: yarn run stylelint
      - run: yarn run build
      - run: yarn run reset-db
      - run: yarn run test:server -- --maxWorkers 4
      - *test-coverage
      - run: yarn run test:jsdom -- --maxWorkers 2
      - *test-coverage
      - *save_cache
  storybook:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: yarn run build-storybook
      - run: cp -r .circleci storybook-static/
      - run: npx storybook-to-ghpages --existing-output-dir=storybook-static

workflows:
  version: 2
  commit:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - storybook:
          requires:
            - test
          filters:
            branches:
              only:
                - master
